//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackupSystem.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public Job()
        {
            this.JobAdHocs = new HashSet<JobAdHoc>();
            this.JobBackupItems = new HashSet<JobBackupItem>();
            this.JobScheduleds = new HashSet<JobScheduled>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string ScheduleType { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<JobAdHoc> JobAdHocs { get; set; }
        public virtual ICollection<JobBackupItem> JobBackupItems { get; set; }
        public virtual ICollection<JobScheduled> JobScheduleds { get; set; }
    }
}
