//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackupSystem.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobAdHoc
    {
        public JobAdHoc()
        {
            this.JobAdHocDates = new HashSet<JobAdHocDate>();
        }
    
        public long ID { get; set; }
        public long JobID { get; set; }
    
        public virtual Job Job { get; set; }
        public virtual ICollection<JobAdHocDate> JobAdHocDates { get; set; }
    }
}
