//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackupSystem.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobScheduledExceptionDate
    {
        public long JobScheduledID { get; set; }
        public System.DateTime ExceptionDateTime { get; set; }
    
        public virtual JobScheduled JobScheduled { get; set; }
    }
}
